### ISSUE TITLE
incorrect insert index?

### ISSUE THREAD

**Issue by gshklover** [belambert/edit-distance#13]
The insert index returned by get_opcodes() appears to be off by -1.

Example:
from difflib import SequenceMatcher
sm = SequenceMatcher(a='abc', b='abdc')
print(sm.get_opcodes())

from edit_distance import SequenceMatcher
sm = SequenceMatcher(a='abc', b='abdc')
print(sm.get_opcodes())

output:
[('equal', 0, 2, 0, 2), ('insert', 2, 2, 2, 3), ('equal', 2, 3, 3, 4)]
[['equal', 0, 1, 0, 1], ['equal', 1, 2, 1, 2], ['insert', 1, 1, 2, 3], ['equal', 2, 3, 3, 4]]

the "insert" opcode index should be 2 (not 1).

**Comment by belambert** [comment]
I think you're right.  I'll take a look.
